services:
  back:
    depends_on:
      postgres:
        condition: service_healthy
    build: 
      context: ./back/.
    #image: ghcr.io/sir-lorrak/note-backend:latest
    container_name: node_app
    ports:
      - ${NODEPORT}:${NODEPORT}
    environment:
      PORT: ${NODEPORT}
      HOST: ${NODEHOST}
      HOSTNAME: ${NODEHOSTNAME}
      # postgres connection information
      PGUSER: ${PGUSER}
      PGHOST: postgres
      PGPASSWORD: ${PGPASSWORD}
      PGDATABASE: ${PGDB}
      PGPORT: ${PGPORT}
      # password for admin user
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    networks:
      - app-network
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  nginx:
    depends_on:
      - back
    container_name: nginx_server
    build: 
      context: ./front/.
    ports:
      - 80:80
    networks:
      - app-network
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  postgres:
    container_name: postgres
    restart: always
    image: postgres
    ports:
      - ${PGPORT}:${PGPORT}
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDB}
    networks:
      - app-network
    volumes:
      - postgres:/data/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${PGDB} -U ${PGUSER}"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --debug --http-api-update
    environment:
      - WATCHTOWER_HTTP_API_TOKEN=${WATCHTOWER_HTTP_API_TOKEN}
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    ports:
      - 8080:8080

volumes:
  postgres:

networks:
  app-network:
    driver: bridge