name: Build Docker Image - Frontend

on:
  schedule:
    - cron: '0 5 * * 1'
  push:
    branches:
      - main
    paths:
      - front/**
      - .github/workflows/docker-build-frontend.yml
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/docker-build-frontend.yml
      - front/**
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    env:
      TITLE: Frontend
      GHCR_SLUG: ghcr.io/sir-lorrak/note-frontend
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.GHCR_SLUG }}
          labels: |
            maintainer=${{ github.repository_owner }}
            org.opencontainers.image.vendor=${{ github.repository_owner }}
            org.opencontainers.image.title=${{ env.TITLE }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1
      -
        name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3.5.0 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push latest
        uses: docker/build-push-action@v6.18.0
        with:
          context: "{{defaultContext}}:front"
          platforms: |
            linux/amd64
            linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.GHCR_SLUG }}:latest
          cache-from: |
            ${{ env.GHCR_SLUG }}:latest