on:
    workflow_call:
        secrets:
            WATCHTOWER_DOMAIN:
                required: true
            WATCHTOWER_HTTP_API_TOKEN:
                required: true
jobs:
    warn:
        runs-on: ubuntu-latest
        steps:
            - name: Curl Watchtower API
              run: |
                curl -s -H "Authorization: Bearer ${{ secrets.WATCHTOWER_HTTP_API_TOKEN }}" ${{ secrets.WATCHTOWER_DOMAIN }}/v1/update