on:
    workflow_call:
        secrets:
            WATCHTOWER_DOMAIN:
                required: true
            WATCHTOWER_HTTP_API_TOKEN:
                required: true
jobs:
    warn:
        runs-on: ubuntu-latest
        steps:
            - name: Curl Watchtower API
              run: |
                curl -s -H "Authorization: Bearer ${{ secrets.WATCHTOWER_HTTP_API_TOKEN }}" ${{ secrets.WATCHTOWER_DOMAIN }}/v1/update
            - name: Purge Cloudflare cache
              run: |
                curl https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_ID }}/purge_cache 
                    -H 'Content-Type: application/json' \
                    -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_TOKEN }}" \
                    -d '{
                        "hosts": [
                            "${{ secrets.CLOUDFLARE_DOMAIN }}"
                        ]
                        }'